---
- hosts: baseinstall:virtualbox
  become: true
  tasks:
    - include: deploy/update_asterisk.yml
- hosts: baseinstall:virtualbox
  become: true
  tasks:
    - include: deploy/update_asterisk_sounds.yml

