VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "default"
  config.vm.box = "centos/8"
  config.vm.synced_folder ".", "/vagrant",
    :mount_options => ["dmode=777,fmode=777"]

  config.vm.provision "baseinstall", type: "ansible" do |ansible|
    ansible.playbook = "deploy/baseinstall_playbook.yml"
    ansible.vault_password_file = "conf/vault_pass_virtualbox.txt"
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    ansible.extra_vars = {
      conf_version: "virtualbox"
    }
    # uncomment for verbose output
    # ansible.raw_arguments = ["-v"]
  end    

  config.vm.provision "install_asterisk_helpers", type: "ansible" do |ansible|
    ansible.playbook = "deploy/install_asterisk_helpers_playbook.yml"
    ansible.vault_password_file = "conf/vault_pass_virtualbox.txt"
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    ansible.extra_vars = {
      conf_version: "virtualbox"
    }
  end    
  
  config.vm.provision "update_asterisk", type: "ansible" do |ansible|
    ansible.playbook = "deploy/update_asterisk_playbook.yml"
    ansible.vault_password_file = "conf/vault_pass_generic.txt"    
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    # uncomment for verbose output
    # ansible.raw_arguments = ["-v"]
  end    

  config.vm.provision "update_asterisk_sip", type: "ansible" do |ansible|
    ansible.playbook = "update_asterisk_sip_playbook.yml"
    ansible.vault_password_file = "conf/vault_pass_virtualbox.txt"    
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    ansible.extra_vars = {
      conf_version: "virtualbox"
    }
    # uncomment for verbose output
    # ansible.raw_arguments = ["-v"]
  end    

  config.vm.provision "update_secrets", type: "ansible" do |ansible|
    ansible.playbook = "deploy/update_secrets_playbook.yml"
    ansible.vault_password_file = "conf/vault_pass_virtualbox.txt"
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    ansible.extra_vars = {
      conf_version: "virtualbox"
    }
  end    
  
  config.vm.provision "post_sync", type: "ansible" do |ansible|
    ansible.playbook = "post_sync_playbook_virtualbox.yml"
    ansible.vault_password_file = "conf/vault_pass_virtualbox.txt"    
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
    ansible.extra_vars = {
      conf_version: "virtualbox"
    }
    # uncomment for verbose output
    # ansible.raw_arguments = ["-v"]
  end    

  config.vm.provision "update_asterisk_itests", type: "ansible" do |ansible|
    ansible.playbook = "update_asterisk_itests_playbook.yml"
    
    # default vm gets virtualbox ansible inventory group
    ansible.groups = {
      "virtualbox" => ["default"]
    }
  end    
  
  # use this environment variable to build with production ssh port/user
  if ENV['vagrantbox'] == 'centos6_32_baseconfig'
    # we put ssh on 42422, so override default 2222 guest port
    config.vm.network "forwarded_port", guest: 42422, host: 2222, id: "ssh"
    # we will want another ssh key for non-virtualbox
    config.ssh.username = "futel"
    config.ssh.private_key_path = "conf/id_rsa"
    # if we put ssh on 42422 and are virtualbox, forward that port
    config.ssh.guest_port = 42422
    config.ssh.port = 2222
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024            # current prod is 512mb, this is for convenience
    # this creates vboxnet0 and vboxnet1, with pingable eth1 on vboxnet1
    config.vm.network "private_network", type: "dhcp", :adapter => 2    
    # uncomment to disable headless mode
    # vb.gui = true
  end

end
