---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
  tasks:
    - include: packages.yml
    - include: users.yml
    - include: config.yml
    - include: install_misc.yml
    - include: install_asterisk.yml
