---
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: find_prod_conf.yml
    - include: find_stage_conf.yml    
