---
- name: determine stage conf version
  shell: echo "{{ prod_conf_version }}" | ./stage_conf_version.py 
  register: conf_version
# We should validate here.
- name: print stage conf version
  debug:
    msg="stage conf version is {{ conf_version.stdout }}"
