---
- name: make asterisk directory
  file:
    path: /opt/asterisk
    state: directory
    owner: asterisk
    group: asterisk
- name: copy asterisk
  synchronize:
    src: "{{ src }}/asterisk-13.38.3"
    dest: /tmp
    delete: yes
    recursive: yes
- name: configure asterisk
  command: ./configure --prefix=/opt/asterisk
  args:
    chdir: /tmp/asterisk-13.38.3
    creates: /tmp/asterisk-13.38.3/makeopts    
- name: create asterisk menuselect config file
  command: make {{ item }}
  args:
    chdir: /tmp/asterisk-13.38.3
  with_items:
    - menuselect.makeopts
# MENUSELECT_PBX
# MENUSELECT_FUNCS
# MENUSELECT_FORMATS
# MENUSELECT_CODECS
- name: run menuselect
  command: \
    menuselect/menuselect \
    --disable-category MENUSELECT_TESTS \
    --disable-category MENUSELECT_CEL \
    --disable-category MENUSELECT_CFLAGS \
    --disable-category MENUSELECT_OPTS_app_voicemail \
    --disable-category MENUSELECT_AGIS \
    --disable-category MENUSELECT_EXTRA_SOUNDS \
    --disable chan_mgcp \
    --disable chan_mobile \
    --disable chan_ooh323 \
    --disable app_amd \
    --disable app_mysql \
    --disable cdr_adaptive_odbc \
    --disable cdr_custom \
    --disable cdr_manager \    
    --disable cdr_mysql \
    --disable cdr_odbc \
    --disable cdr_pgsql \
    --disable cdr_radius \
    --disable cdr_sqlite \
    --disable cdr_sqlite3_custom \
    --disable cdr_syslog \
    --disable cdr_tds \
    --disable res_ari \
    --disable res_config_mysql \
    --disable res_hep \
    --disable res_phoneprov \
    --disable res_parking \    
    --disable res_statsd
  args:
    chdir: /tmp/asterisk-13.38.3
- name: make asterisk
  command: make
  args:
    chdir: /tmp/asterisk-13.38.3
    creates: /tmp/asterisk-13.38.3/main    
- name: install asterisk
  command: make install
  args:
    chdir: /tmp/asterisk-13.38.3
    creates: /opt/asterisk/sbin/asterisk
- name: make asterisk config, including system scripts
  command: make config
  args:
    chdir: /tmp/asterisk-13.38.3
    creates: /etc/init.d/asterisk
- name: copy service config
  copy:
    src: "{{ src }}/etc/sysconfig/asterisk"
    dest: /etc/sysconfig/asterisk
- name: make asterisk log archive directory
  file:
    path: /opt/asterisk/var/log/asterisk/old
    state: directory
    owner: asterisk
    group: asterisk
- name: change file ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: asterisk
    group: asterisk
    recurse: yes
  with_items:
    - /opt/asterisk/etc/asterisk
    - /opt/asterisk/var/lib/asterisk
    - /opt/asterisk/var/log/asterisk    
    - /opt/asterisk/var/run/asterisk    
    - /opt/asterisk/var/spool/asterisk
- name: enable but do not yet start asterisk
  service:
    name: asterisk
    enabled: yes
