---
- name: make asterisk directory
  file:
    path: /opt/asterisk
    state: directory
    owner: asterisk
    group: asterisk
- name: unpack asterisk
  unarchive:
    src: "{{ src }}/asterisk-13-current.tar.gz"
    dest: /tmp
    owner: asterisk
    group: asterisk
    creates: /tmp/asterisk-13.25.0
- name: configure asterisk
  command: sudo -u asterisk ./configure --libdir=/opt/asterisk/lib64 --prefix=/opt/asterisk --exec_prefix=/opt/asterisk
  args:
    chdir: /tmp/asterisk-13.25.0
    creates: /tmp/asterisk-13.25.0/makeopts    
# what a crock!  Some of these may be superstition.    
- name: configure asterisk menuselect things
  command: sudo -u asterisk make {{ item }}
  args:
    chdir: /tmp/asterisk-13.25.0
  with_items:
    - menuselect.makeopts
# virtualbox, digital ocean, and probably all virtual providers disbable native
# optimizations
- name: run menuselect
  command: sudo -u asterisk menuselect/menuselect --disable BUILD_NATIVE menuselect.makeopts
  args:
    chdir: /tmp/asterisk-13.25.0
# XXX this creates is already there?
# We're changed=false here and just doing this on the install?
- name: make asterisk
  command: sudo -u asterisk make
  args:
    chdir: /tmp/asterisk-13.25.0
    creates: /tmp/asterisk-13.25.0/main    
- name: install asterisk
  command: sudo -u asterisk make install
  args:
    chdir: /tmp/asterisk-13.25.0
    creates: /opt/asterisk/sbin/asterisk
- name: make asterisk samples
  command: sudo -u asterisk make samples
  args:
    chdir: /tmp/asterisk-13.25.0
    creates: /opt/asterisk/etc/asterisk/extensions.conf
- name: make asterisk config, as root
  command: make config
  args:
    chdir: /tmp/asterisk-13.25.0
    creates: /etc/init.d/asterisk
# this adds ASTARGS="-U asterisk"
- name: copy our safe_asterisk
  copy:
    src: "{{ src }}/safe_asterisk"
    dest: /opt/asterisk/sbin
- name: make asterisk log archive directory
  file:
    path: /opt/asterisk/var/log/asterisk/old
    state: directory
    owner: asterisk
    group: asterisk
- name: enable but do not yet start asterisk
  service:
    name: asterisk
    enabled: yes
