---
- name: add logrotate job
  copy:
    src: ../src/logrotate/logrotate.d/asterisk
    dest: /etc/logrotate.d/asterisk
- name: make futel directory
  file:
    path: /opt/futel
    state: directory
    owner: asterisk
    group: asterisk
- name: make source directory
  file:
    path: /opt/futel/src
    state: directory
    owner: asterisk
    group: asterisk
- name: install event listener
  copy:
    src: ../src/eventlistener.py
    dest: /opt/futel/src
    owner: asterisk
    group: asterisk
    mode: "a+x"    
- name: set up supervisord conf
  copy:
    src: ../src/supervisord.conf
    dest: /etc/supervisord.conf
    owner: root
    group: root
# enable but do not yet start supervisord
- name: enable supervisord service
  service:
    name: supervisord
    enabled: yes
