---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: install_asterisk_helpers.yml
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: install_asterisk_helpers.yml
