---
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: lock.yml
- hosts: virtualbox
  become: true
  tasks:
    - include: lock.yml
