---
# distro package setup and installation
- name: install selinux bindings, required since we start with selinux
  yum:
    name: python3-libselinux
    state: present 
- name: remove yum packages
  yum:
    name:
      - audit
      - rpcbind
      - selinux-policy
      - selinux-policy-targeted
      - sendmail
    state: absent
- name: install epel yum package
  yum:
    name:
      - epel-release
- name: update yum
  yum:
    name: "*"
    state: latest
# should be replaced with "enablerepo: powertools" when installing packages?
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: install yum packages
  yum:
    name:
      - iptables-services
      - firewalld
      - chrony
      - man
      - mpg123
      - vim-enhanced
      - gcc
      - gcc-c++
      - SDL
      - make
      - automake
      - libtool
      - autoconf
      - mlocate
      - strace
      - ltrace
      - wget
      - lsof
      - tcpdump
      - openssh
      - openssh-server
      - openssh-clients
      - openssl-devel
      - ncurses-devel
      - libxml2-devel
      - lua-devel
      - newt-devel
      - kernel-devel
      - sqlite-devel
      - libuuid-devel
      - supervisor
      - cyrus-sasl-plain
      - python3-yaml
      - python3-pip
      - postfix
      - redis
      - jansson-devel
      - espeak-ng
      - patch
      - libedit-devel
      # for asterisk build, many of these probably not needed
      - pkgconfig
      - speex-devel
      - speexdsp-devel
      - libogg-devel
      - libvorbis-devel
      - alsa-lib-devel
      - portaudio-devel
      - libcurl-devel
      - xmlstarlet
      - bison
      - flex
      - postgresql-devel
      - unixODBC-devel
      - neon-devel
#      - gmime-devel
      - uriparser-devel
      - libxslt-devel
      - mysql-devel
      - bluez-libs-devel
      - radcli-devel
      - freetds-devel
      - jack-audio-connection-kit-devel
      - libcap-devel
      - net-snmp-devel
#      - iksemel-devel
#      - corosynclib-devel
      - popt-devel
      - libical-devel
      - spandsp-devel
      - libresample-devel
      - uw-imap-devel
      - binutils-devel
      - libsrtp-devel
      - gsm-devel
      - doxygen
      - graphviz
      - openldap-devel
#      - hoard
      - codec2-devel
      - fftw-devel
      - libsndfile-devel
      - unbound-devel
      - subversion
    state: present
- name: update pip packages
  pip:
    name:
      - boto3
      - redis
      - pyst
    state: present

