---
# distro package setup and installation
- name: install selinux bindings, required since we start with selinux
  yum:
    name: python3-libselinux
    state: present 
- name: remove yum packages
  yum:
    name:
      - audit
      - rpcbind
      - selinux-policy
      - selinux-policy-targeted
      - sendmail
    state: absent
- name: install epel yum package
  yum:
    name:
      - epel-release
- name: update yum
  yum:
    name: "*"
    state: latest
# should be replaced with "enablerepo: powertools" when installing packages?
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: install yum packages
  yum:
    name:
      - iptables-services
      - firewalld
      - chrony
      - man
      - vim-enhanced
      - gcc
      - gcc-c++
      - SDL
      - make
      - automake
      - libtool
      - autoconf
      - mlocate
      - strace
      - ltrace
      - wget
      - lsof
      - tcpdump
      - openssh
      - openssh-server
      - openssh-clients
      - openssl-devel
      - ncurses-devel
      - libxml2-devel
      - lua-devel
      - newt-devel
      - kernel-devel
      - sqlite-devel
      - libuuid-devel
      - supervisor
      - logwatch
      - cyrus-sasl-plain
      - python3-yaml
      - python3-pip
      - postfix
      - redis
      - jansson-devel
      - espeak-ng
    state: present
- name: update pip
  pip:
    name: pip
    state: latest
- name: update pip packages
  pip:
    name:
      - boto3
      - redis
      - pyst
    state: present

