---
- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
- name: write sshd config
  copy:
    src: src/sshd_config
    dest: /etc/ssh/sshd_config
- name: restart sshd
  service:
    name: sshd
    state: restarted
- name: enable iptables
  service:
    name: iptables
    enabled: yes
- name: enable ip6tables
  service:
    name: ip6tables
    enabled: yes
- name: update iptables rules
  script: src/iptables.sh
- name: update ip6tables rules
  script: src/ip6tables.sh
- name: save iptables rules
  shell: iptables-save >/etc/sysconfig/iptables
- name: save ip6tables rules
  shell: ip6tables-save >/etc/sysconfig/ip6tables
- name: start iptables
  service:
    name: iptables
    state: restarted
- name: start ip6tables
  service:
    name: ip6tables
    state: restarted
