---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
  tasks:
    - include: users.yml
    - include: secure.yml
- hosts: prod
  become: true
  vars:
    src: "../src"
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: users.yml  
    - include: secure.yml
- hosts: virtualbox
  become: true
  tasks:
    - include: secure_virtualbox.yml
