# We are using iptables, the more modern toolkit is firewalld and we may
# need to convert to that at some point.
---
- name: stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
- name: write sshd config
  copy:
    src: ../src/sshd_config
    dest: /etc/ssh/sshd_config
- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
- name: enable iptables
  ansible.builtin.systemd:
    name: iptables
    enabled: yes
- name: enable ip6tables
  ansible.builtin.systemd:
    name: ip6tables
    enabled: yes
- name: update iptables rules
  script: ../src/iptables.sh
- name: update ip6tables rules
  script: ../src/ip6tables.sh
- name: save iptables rules
  shell: iptables-save >/etc/sysconfig/iptables
- name: save ip6tables rules
  shell: ip6tables-save >/etc/sysconfig/ip6tables
- name: start iptables
  ansible.builtin.systemd:
    name: iptables
    state: restarted
- name: start ip6tables
  ansible.builtin.systemd:
    name: ip6tables
    state: restarted
