---
- hosts: localhost
  tasks:
    - include: pre_sync_from_prod.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: sync_from_prod.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: pre_sync_to_stage.yml
    - include: sync_to_stage.yml
