---
- name: load conf
  include_vars: "conf.yml"
- name: make recordings directory
  file:
    path: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    state: directory
    owner: asterisk
    group: asterisk
- name: make es directory
  file:
    path: /opt/asterisk/var/lib/asterisk/sounds/es
    state: directory
    owner: asterisk
    group: asterisk
- name: link en sounds
  file:
    src: "{{ virtualbox_sound_directory }}/en/{{ item }}"
    dest: "{{ deployed_sound_directory }}/en/{{ item }}"
    state: link
  with_items: "{{ sound_items_en }}"
- name: link es sounds
  file:
    src: "{{ virtualbox_sound_directory }}/es/{{ item }}"
    dest: "{{ deployed_sound_directory }}/es/{{ item }}"
    state: link
  with_items: "{{ sound_items_es }}"
- name: link futel sounds
  file:
    src: "{{ virtualbox_sound_directory }}/futel/{{ item }}"
    dest: "{{ deployed_sound_directory }}/futel/{{ item }}"
    state: link
  with_items: "{{ sound_items_futel }}"
# we do not currently keep MOH in the futel-content repo, just copy
- name: copy music on hold
  copy:
    src: "../src/var/lib/asterisk/moh/{{ item }}"
    dest: "{{ deployed_moh_directory }}"
    owner: asterisk
    group: asterisk
  with_items: "{{ moh_items }}"
