# We are using iptables, the more modern toolkit is firewalld and we may
# need to convert to that at some point.
---
- name: update iptables rules
  script: ../src/iptables.sh
- name: update ip6tables rules
  script: ../src/ip6tables.sh
- name: save iptables rules
  shell: iptables-save >/etc/sysconfig/iptables
- name: save ip6tables rules
  shell: ip6tables-save >/etc/sysconfig/ip6tables
- name: restart iptables
  ansible.builtin.systemd:
    name: iptables
    state: restarted
- name: restart ip6tables
  ansible.builtin.systemd:
    name: ip6tables
    state: restarted
