---
# - hosts: baseinstall
#   become: true
#   vars:
#     src: "../src"
#   tasks:
#     - include: packages.yml
#     - include: build.yml    
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: packages.yml
    - include: build.yml