---
- name: update dnf
  dnf:
    name: "*"
    state: latest
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: install dnf packages
  dnf:
    name:
      # RPM building requirements.
      - rpmdevtools
      - rpmlint
      # Requirements for building the asterisk RPM. Hopefully we
      # removed everything we aren't building and didn't remove anything
      # we are building.
      - autoconf
      - automake
      - gcc
      - gcc-c++
      - ncurses
      - perl
      - openssl-devel
      - newt-devel
      - ncurses-devel
      - libcap-devel
#      - gtk2-devel
      - libsrtp-devel
      - perl-interpreter
      - perl-generators
      - popt-devel
      - systemd
      - kernel-headers
#      - gmime-devel
#      - doxygen
#      - graphviz
      - libxml2-devel
#      - latex2html
#      - neon-devel
#      - libical-devel
#      - libxml2-devel
#      - speex-devel >= 1.2
#      - speexdsp-devel >= 1.2
      - libogg-devel
      - libvorbis-devel
      - gsm-devel
      - SDL-devel
#      - SDL_image-devel
      - libedit-devel
      - ilbc-devel
      - libuuid-devel
#      - unbound-devel
#      - corosynclib-devel
      - alsa-lib-devel
      - libcurl-devel
      - dahdi-tools-devel >= 2.0.0
      - dahdi-tools-libs >= 2.0.0
      - libpri-devel >= 1.4.12
      - libss7-devel >= 1.0.1
      - spandsp-devel >= 0.0.5-0.1.pre4
      - libtiff-devel
      - libjpeg-turbo-devel
      - lua-devel
      - jack-audio-connection-kit-devel
      - libresample-devel
      - bluez-libs-devel
      - libtool-ltdl-devel
      - portaudio-devel >= 19
      - sqlite-devel
      - freetds-devel
#      - mISDN-devel
#      - openldap-devel
#      - mariadb-devel
#      - mariadb-connector-c-devel
#      - libtool-ltdl-devel
#      - unixODBC-devel
#      - postgresql-devel
#      - libpq-devel
#      - freeradius-client-devel
#      - radcli-compat-devel
      - net-snmp-devel
      - lm_sensors-devel
#      - uw-imap-devel
      - jansson-devel
      - libgcrypt
      - make
