---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: packages.yml
    - include_tasks: config.yml
    - include_tasks: install_misc.yml
    - include_tasks: install_asterisk.yml
    - include_tasks: install_asterisk_helpers.yml    
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include_tasks: packages.yml
    - include_tasks: users.yml
    - include_tasks: config.yml
    - include_tasks: install_misc.yml
    - include_tasks: install_asterisk.yml
    - include_tasks: install_asterisk_helpers.yml
- hosts: digitalocean
  tasks:
    - include_tasks: build_volume.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: provision_storage.yml  
