---
# misc config of distro packages
- name: write postfix config
  copy:
    src: "{{ src }}/postfix/main.cf"
    dest: /etc/postfix/main.cf
- name: restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
- name: set timezone with zoneinfo
  file:
    src: /usr/share/zoneinfo/US/Pacific
    dest: /etc/localtime
    state: link
    force: yes
- name: set timezone with clock config
  copy:
    src: "{{ src }}/clock"
    dest: /etc/sysconfig/clock
    force: yes
- name: start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes    
- name: enable and start redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes
