---
- hosts: digitalocean
  tasks:
    - include_tasks: deploy_digitalocean.yml
    - include_tasks: dns.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: find_prod_conf.yml
- hosts: local
  tasks:
    - include_tasks: write_prod_conf.yml  
    - include_tasks: find_stage_conf.yml
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
  tasks:
    - include_tasks: write_stage_conf.yml
    - include_tasks: users.yml
    - include_tasks: secure.yml
    - include_tasks: update_iptables.yml    
- hosts: virtualbox
  become: true
  tasks:
    - include_tasks: secure_virtualbox.yml
