---
- name: load secrets
  include_vars: "deploy_digitalocean_secrets_digitalocean.yml"
  no_log: true
# This is just my key, we are assuming ansible is being run by me.
# Other users would need their keys in the DigitalOcean org settings.
# This key is used for the initial droplet setup, before SSH is updated.
- name: assert ssh key is present
  digital_ocean_sshkey:
    state: present
    name: karl@shahat
    ssh_pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKKfK9+6aHXk5vIRIeJyYW9uBL6cgdljfUAecBeKZj84 karl@shahat
    oauth_token: "{{ deploy_access_token }}"
  register: ssh_key
- name: create stage droplet
  digital_ocean_droplet:
    state: present
    name: futel-stage.phu73l.net
    unique_name: yes
    size: s-1vcpu-1gb
    region: sfo3
    image: rockylinux-8-x64
    monitoring: yes
    ssh_keys: ["{{ ssh_key.data.ssh_key.fingerprint }}"]
    oauth_token: "{{ deploy_access_token }}"
  register: droplet
