---
- name: find prod conf version
  command: grep -o "foo\|bar" /etc/asterisk/pjsip_secret_flavored.conf
  register: reg
- name: set fact for prod conf version
  ansible.builtin.set_fact:
    prod_conf_version: "{{ reg }}"
