---
- name: make ld.so.conf see locally installed libs
  lineinfile:
    dest: /etc/ld.so.conf.d/usr_local.conf
    line: "/usr/local/lib"
    create: yes
- name: run ldconfig on updated ld.so.conf
  command: /sbin/ldconfig
