---
- name: add logrotate job
  copy:
    src: ../src/etc/logrotate/logrotate.d/asterisk
    dest: /etc/logrotate.d/asterisk
- name: make futel directories
  file:
    path: /opt/futel
    state: directory
    owner: asterisk
    group: asterisk
- name: make futel directories
  file:
    path: /opt/futel/src
    state: directory
    owner: asterisk
    group: asterisk
- name: make futel directories
  file:
    path: /opt/futel/bin
    state: directory
    owner: asterisk
    group: asterisk
- name: make futel directories
  file:
    path: /opt/futel/var
    state: directory
    owner: asterisk
    group: asterisk
- name: make futel directories
  file:
    path: /opt/futel/var/run
    state: directory
    owner: asterisk
    group: asterisk
- name: install lock utility
  copy:
    src: ../src/opt/futel/bin/lock.lua
    dest: /opt/futel/bin
    owner: asterisk
    group: asterisk
    mode: "a+x"
- name: install reporting utilities
  copy:
    src: ../src/opt/futel/src/{{ item }}
    dest: /opt/futel/src
    owner: asterisk
    group: asterisk
    mode: "a+x"
  with_items:
    - confbridge_encourager.py
    - contact_publisher.py
    - contact_status.py
    - eventlistener.py
    - snspublish.py
- name: set up supervisord conf
  copy:
    src: ../src/etc/supervisord.conf
    dest: /etc/supervisord.conf
    owner: root
    group: root
# enable but do not yet start supervisord
- name: enable supervisord service
  ansible.builtin.systemd:
    name: supervisord
    enabled: yes
