---
# distro package setup and installation
- name: remove yum packages
  yum:
    name:
      - asterisk
      - audit
      - cockpit-bridge
      - cockpit-ws
      - cpp
      - dejavu-fonts-common
      - dejavu-sans-mono-fonts
      - dracut-squash
      - diffutils
      - droplet-agent
      - emacs-filesystem
      - freetype
      - geolite2-city
      - geolite2-country
      - libX11
      - libX11-common
      - libX11-xcb
      - libXau
      - man-db
      - man-pages
      - man-pages-overrides
      - rpcbind
      - sendmail
      - telnet
      - xkeyboard-config
    state: absent
    autoremove: yes    
# should be replaced with "enablerepo: powertools" when installing packages?
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: install yum packages
  yum:
    name:
      - chrony
      - lua
      - mpg123
      - rsync
      - sox
      - SDL
      - openssh
      - openssh-server
      - supervisor
      - python3-yaml
      - python3-pip
      - postfix
      - redis
      - espeak-ng
    state: present
- name: update a chunk of yum
  yum:
    name:
      - acl
      - alsa-lib
      - authselect
      - authselect-compat
      - authselect-libs
      - basesystem
    state: latest
- name: update a chunk of yum
  yum:
    name:
      - glibc
      - glibc-all-langpacks
      - glibc-common
      - glibc-gconv-extra
    state: latest
- name: update a chunk of yum
  yum:
    name:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-tools      
    state: latest
- name: update a chunk of yum
  yum:
    name:
      - linux-firmware
    state: latest
- name: update the remaining yum
  yum:
    name: "*"
    state: latest
- name: update pip packages
  pip:
    name:
      - boto3
      - redis
      - pyst
    state: present

