---
# distro package setup and installation
- name: remove yum packages
  yum:
    name:
      - asterisk
      - audit
      - cockpit-bridge
      - cockpit-ws
      - cpp
      - dejavu-fonts-common
      - dejavu-sans-mono-fonts
      - diffutils
      - emacs-filesystem
      - freetype
      - geolite2-city
      - geolite2-country
      - libX11
      - libX11-common
      - libX11-xcb
      - libXau
      - man-db
      - man-pages
      - man-pages-overrides
      - rpcbind
      - sendmail
      - telnet
      - xkeyboard-config
    state: absent
    autoremove: yes
- name: install yum packages
  yum:
    name:
      - chrony
      - lua
      - mpg123
      - rsync
      - sox
      - SDL
      - openssh
      - openssh-server
      - supervisor
      - python3-yaml
      - python3-pip
      - postfix
      - redis
      - espeak-ng
    state: present
- name: update yum
  yum:
    name: "*"
    state: latest
# XXX is this still needed? It's out of order now...
# should be replaced with "enablerepo: powertools" when installing packages?
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: update pip packages
  pip:
    name:
      - boto3
      - redis
      - pyst
    state: present

