---
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: lock.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: hostname_stage.yml  
- hosts: prod
  become: true
  tasks:
    - include_tasks: hostname_prod.yml
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
- hosts: local
  tasks:
    - include_tasks: pre_sync_from_prod.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: sync_from_prod.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: pre_sync_to_stage.yml
    - include_tasks: sync_to_stage.yml
    - include_tasks: post_sync.yml
- hosts: digitalocean
  tasks:
    - include_tasks: post_sync_dns.yml
