---
- hosts: digitalocean
  tasks:
    - include: build_volume.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: provision_storage.yml  
