---
- name: have apt packages
  apt:
    name:
      - libgsl-dev
      - ruby-dev
      - normalize-audio
      - sndfile-programs
      - python3-pip
      - libsox-fmt-mp3
      - sox
      - lame
- name: have pip packages
  pip:
    name:
      - pyyaml
      - dopy
    state: present
