---
- name: check for conf file
  stat:
    path: ../conf/vault_pass_generic.txt
  register: r
- name: fail without conf file
  fail:
    msg: "conf/vault_pass_generic is required"
  when: not r.stat.exists
- name: check for conf file
  stat:
    path: ../conf/vault_pass_virtualbox.txt
  register: r
- name: fail without conf file
  fail:
    msg: "conf/vault_pass_virtualbox is required"
  when: not r.stat.exists
    
