---
- name: print stage conf version
  debug:
    msg="stage conf version is {{ conf_version }}"
- name: load secrets
  include_vars: "install_asterisk_helpers_secrets_{{ conf_version }}.yml"
  no_log: true
- name: load secrets
  include_vars: "update_asterisk_secrets_{{ conf_version }}.yml"
  no_log: true
# for install_asterisk_helpers.yml
- name: install event listener conf which is local or has secrets
  template:
    src: ../src/opt/futel/src/eventlistenerconf.py.j2
    dest: /opt/futel/src/eventlistenerconf.py
    owner: asterisk
    group: asterisk
- name: copy voip provider conf with secrets
  template:
    src: ../src/etc/asterisk/pjsip_secret_flavored.conf.j2    
    dest: /etc/asterisk/pjsip_secret_flavored.conf
    owner: asterisk
    group: asterisk
- name: copy iax conf with secrets
  template:
    src: ../src/etc/asterisk/iax_secret_flavored.conf.j2    
    dest: /etc/asterisk/iax_secret_flavored.conf
    owner: asterisk
    group: asterisk
