---
- name: load flavored secrets
  include_vars: "update_asterisk_secrets_generic.yml"
  no_log: true
- name: delete asterisk conf
  file:
    path: /etc/asterisk
    state: absent
- name: delete asterisk conf
  file:
    path: /etc/asterisk
    state: directory
    owner: asterisk
    group: asterisk
- name: copy asterisk conf
  copy:
    src: ../src/etc/asterisk/
    dest: /etc/asterisk
    owner: asterisk
    group: asterisk
- name: copy pjsip conf with secrets
  template:
    src: ../src/etc/asterisk/pjsip_secret.conf.j2
    dest: /etc/asterisk/pjsip_secret.conf
    owner: asterisk
    group: asterisk
- name: copy dialplan conf with secrets
  template:
    src: ../src/etc/asterisk/extensions_secret.conf.j2
    dest: /etc/asterisk/extensions_secret.conf
    owner: asterisk
    group: asterisk
- name: copy followme conf with secrets
  template:
    src: ../src/etc/asterisk/followme_secret.conf.j2
    dest: /etc/asterisk/followme_secret.conf
    owner: asterisk
    group: asterisk
- name: copy blocklist conf with secrets
  template:
    src: ../src/etc/asterisk/blocklist.yaml.j2
    dest: /etc/asterisk/blocklist.yaml
    owner: asterisk
    group: asterisk
- name: copy manager conf with secrets
  template:
    src: ../src/manager.conf.j2
    dest: /etc/asterisk/manager.conf
- name: copy asterisk scripts
  copy:
    src: ../src/var/lib/asterisk/agi-bin/
    dest: /var/lib/asterisk/agi-bin
    owner: asterisk
    group: asterisk
- name: make asterisk scripts executable
  file:
    path: /var/lib/asterisk/agi-bin
    mode: "u+x"
    recurse: yes
