---
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: link_asterisk_sounds.yml
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: extract_assets.yml    
    - include: link_asterisk_sounds.yml
