---
- name: load conf
  include_vars: "conf.yml"
- name: copy futel sounds
  copy:
    src: "{{ asterisk_sound_directory }}/futel/{{ item }}"
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
  with_items:    
    - williams-short
    - williams-long
    - oracle-dead-interstitial-short
    - oracle-dead-interstitial-long
    - oracle-dead-oracle
    - wildcard-line
    - church-of-robotron
    - conversations
    - longmont
    - sequence-challenge
- name: make en statements directory
  file:
    path: /var/lib/asterisk/sounds/en/statements
    state: directory
    owner: asterisk
    group: asterisk
- name: make es statements directory
  file:
    path: /var/lib/asterisk/sounds/es/statements
    state: directory
    owner: asterisk
    group: asterisk
- name: copy en statement sounds
  copy:
    src: "{{ asterisk_sound_directory }}/en/statements/{{ item }}"
    dest: /var/lib/asterisk/sounds/en/statements
    owner: asterisk
    group: asterisk
  with_items:
    - anzie-wumpus
    - challenge
    - conversations
    - karl-oracle-dead
    - karl_quuux
    - konami
    - karl-robotron
    - karl-voicemail-ivr
    - karl-wildcard-line
    - rose-bar
    - rose-foo
    - sailor
    - tishbite
    - tishbite-wait
- name: copy es statement sounds
  copy:
    src: "{{ asterisk_sound_directory }}/es/statements/{{ item }}"  
    dest: /var/lib/asterisk/sounds/es/statements
    owner: asterisk
    group: asterisk
  with_items:
    - sailor
    - sofia-community
    - sofia-community-service
    - sofia-directory
    - sofia-general
    - sofia-incoming
    - sofia-information
    - sofia-network
    - sofia-outgoing
    - sofia-utilities
    - sofia-voicemail
- name: copy en asterisk confbridge menu sounds
  copy:
    src: "{{ asterisk_sound_directory }}/en/futelconf"
    dest: /var/lib/asterisk/sounds/en
    owner: asterisk
    group: asterisk
- name: copy hold music
  copy:
    src: ../src/var/lib/asterisk/moh/{{ item }}/
    dest: /var/lib/asterisk/moh/{{ item }}
    owner: asterisk
    group: asterisk
  with_items:
    - hold
    - operator
    - midi
- name: make recordings directory
  file:
    path: /var/lib/asterisk/sounds/futel/recordings
    state: directory
    owner: asterisk
    group: asterisk
