---
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: link_asterisk_sounds.yml
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: extract_assets.yml    
    - include: link_asterisk_sounds.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: find_prod_conf.yml
- hosts: local
  tasks:
    - include: write_prod_conf.yml  
    - include: find_stage_conf.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: write_stage_conf.yml
    - include: update_secrets.yml
- hosts: virtualbox
  become: true
  tasks:
    - include: write_stage_conf_virtualbox.yml
    - include: update_secrets.yml
- hosts: local
  tasks:
    - include: pre_sync_from_prod.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: sync_from_prod.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: pre_sync_to_stage.yml
    - include: sync_to_stage.yml
    - include: post_sync.yml
- hosts: virtualbox
  become: true
  tasks:
    - include: post_sync.yml
