---
- name: load conf
  include_vars: "conf.yml"
- name: make recordings directory
  file:
    path: /var/lib/asterisk/sounds/futel/recordings
    state: directory
    owner: asterisk
    group: asterisk
- name: copy asterisk williams short sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/williams-short
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk williams long sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/williams-long
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk long oracle sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/oracle-dead-interstitial-long
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk short oracle sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/oracle-dead-interstitial-short
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk oracle oracle sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/oracle-dead-oracle
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: make en statements directory
  file:
    path: /var/lib/asterisk/sounds/en/statements
    state: directory
    owner: asterisk
    group: asterisk
- name: make es statements directory
  file:
    path: /var/lib/asterisk/sounds/es/statements
    state: directory
    owner: asterisk
    group: asterisk
- name: copy en statement sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/en/statements/{{ item }}
    dest: /var/lib/asterisk/sounds/en/statements
    owner: asterisk
    group: asterisk
  with_items:
    - anzie-wumpus
    - challenge
    - conversations
    - karl-oracle-dead
    - karl_quuux
    - konami
    - karl-robotron
    - karl-voicemail-ivr
    - karl-wildcard-line
    - rose-bar
    - rose-foo
    - sailor
    - tishbite
    - tishbite-wait
- name: copy es statement sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/es/statements/{{ item }}
    dest: /var/lib/asterisk/sounds/es/statements
    owner: asterisk
    group: asterisk
  with_items:
    - sailor
    - sofia-community
    - sofia-community-service
    - sofia-directory
    - sofia-general
    - sofia-incoming
    - sofia-information
    - sofia-network
    - sofia-outgoing
    - sofia-utilities
    - sofia-voicemail
- name: copy asterisk wildcard line sounds
  copy:
    src: ../src/var/lib/asterisk/sounds/futel/wildcard-line
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy sounds
  copy:
    src: "{{ asterisk_sound_directory }}/futel/{{ item }}"
    dest: /var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
  with_items:
    - church-of-robotron
    - conversations
    - longmont
    - sequence-challenge
- name: copy asterisk confbridge menu sounds
  copy:
    src: "{{ asterisk_sound_directory }}/en/futelconf"
    dest: /var/lib/asterisk/sounds/en
    owner: asterisk
    group: asterisk
- name: copy asterisk hold music
  copy:
    src: ../src/var/lib/asterisk/moh/hold/
    dest: /var/lib/asterisk/moh/hold
    owner: asterisk
    group: asterisk
- name: copy operator hold music
  copy:
    src: ../src/var/lib/asterisk/moh/operator/
    dest: /var/lib/asterisk/moh/operator
    owner: asterisk
    group: asterisk
- name: copy midi hold music
  copy:
    src: ../src/var/lib/asterisk/moh/midi/
    dest: /var/lib/asterisk/moh/midi
    owner: asterisk
    group: asterisk
