---
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: find_prod_conf.yml
- hosts: local
  tasks:
    - include_tasks: write_prod_conf.yml  
    - include_tasks: find_stage_conf.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: write_stage_conf.yml
    - include_tasks: update_secrets.yml
- hosts: virtualbox
  become: true
  tasks:
    - include_tasks: write_stage_conf_virtualbox.yml
    - include_tasks: update_secrets.yml
- hosts: metal
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: write_stage_conf_metal.yml
    - include_tasks: update_secrets.yml
- hosts: local
  tasks:
    - include_tasks: pre_sync_from_prod.yml
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: sync_from_prod.yml
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: pre_sync_to_stage.yml
    - include_tasks: sync_to_stage.yml
    - include_tasks: post_sync.yml
- hosts: virtualbox
  become: true
  tasks:
    - include_tasks: pre_sync_to_stage.yml  
    - include_tasks: post_sync.yml
