---
- hosts: prod
  become: true
  vars:
    src: "../src"
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include_tasks: update_iptables.yml
