---
- name: load conf
  include_vars: "conf.yml"
- name: clean sounds directories
  file:
    path: "{{ src }}/var/lib/asterisk/sounds"
    state: absent
- name: clean sounds directories
  file:
    path: "{{ src }}/var/lib/asterisk/sounds"
    state: directory
- name: update and copy sounds
  command: ruby scripts/update_audio_assets.rb {{ src }}/{{ item }} {{ asset_directory }}/{{ item }}
  with_items:
    - var/lib/asterisk/sounds/futel/church-of-robotron
    - var/lib/asterisk/sounds/futel/conversations
    - var/lib/asterisk/sounds/futel/longmont
    - var/lib/asterisk/sounds/futel/oracle-dead-interstitial-long
    - var/lib/asterisk/sounds/futel/oracle-dead-interstitial-short
    - var/lib/asterisk/sounds/futel/oracle-dead-oracle
    - var/lib/asterisk/sounds/futel/sequence-challenge
    - var/lib/asterisk/sounds/futel/wildcard-line
    - var/lib/asterisk/sounds/futel/williams-long
    - var/lib/asterisk/sounds/futel/williams-short
    - var/lib/asterisk/sounds/en/statements/anzie-wumpus
    - var/lib/asterisk/sounds/en/statements/challenge
    - var/lib/asterisk/sounds/en/statements/conversations
    - var/lib/asterisk/sounds/en/statements/karl-oracle-dead
    - var/lib/asterisk/sounds/en/statements/karl_quuux
    - var/lib/asterisk/sounds/en/statements/karl-robotron
    - var/lib/asterisk/sounds/en/statements/karl-voicemail-ivr
    - var/lib/asterisk/sounds/en/statements/karl-wildcard-line
    - var/lib/asterisk/sounds/en/statements/konami
    - var/lib/asterisk/sounds/en/statements/rose-bar
    - var/lib/asterisk/sounds/en/statements/rose-foo
    - var/lib/asterisk/sounds/en/statements/sailor
    - var/lib/asterisk/sounds/en/statements/tishbite
    - var/lib/asterisk/sounds/en/statements/tishbite-wait
    - var/lib/asterisk/sounds/en/futelconf
    - var/lib/asterisk/sounds/es/statements/sailor
    - var/lib/asterisk/sounds/es/statements/sofia-community
    - var/lib/asterisk/sounds/es/statements/sofia-community-service
    - var/lib/asterisk/sounds/es/statements/sofia-directory
    - var/lib/asterisk/sounds/es/statements/sofia-general
    - var/lib/asterisk/sounds/es/statements/sofia-incoming
    - var/lib/asterisk/sounds/es/statements/sofia-information
    - var/lib/asterisk/sounds/es/statements/sofia-network
    - var/lib/asterisk/sounds/es/statements/sofia-outgoing
    - var/lib/asterisk/sounds/es/statements/sofia-utilities
    - var/lib/asterisk/sounds/es/statements/sofia-voicemail
