---
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: update_asterisk_sounds.yml
    - include: update_asterisk_cruft.yml
- hosts: virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: update_asterisk.yml
    - include: update_asterisk_sounds_virtualbox.yml
