VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder ".", "/vagrant",
    :mount_options => ["dmode=777,fmode=777"]

  if ENV['vagrantbox'] == 'vpnbox'
  	# bootstrap vpn box from centos6_32_baseconfig
	config.vm.network "forwarded_port", guest: 42422, host: 2222, id: "ssh"
	config.ssh.username = "futel"
	config.ssh.private_key_path = "conf/id_rsa"
	config.ssh.guest_port = 42422
	config.ssh.port = 2222
	config.vm.box = "centos6_32_baseconfig"
	config.vm.provision :shell, :path => "src/build/make_vpnbox.sh"

  end

  config.vm.provider :virtualbox do |vb|
    # uncomment to disable headless mode
    #vb.gui = true
    config.vm.network :public_network, :bridge => 'wlan0'
  end

end
