#!/bin/bash
# jackd         Init script for jack daemon
#
# Author:       futel
#
# description:  starts jackd
# processname:  jackd

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

USER=asterisk

# sudo -u asterisk /usr/local/bin/jackd
JACKD_OPTS="-R -d dummy -r 16000"
JACKD=/usr/local/bin/jackd
RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting jackd..."
    daemon --user ${USER} --pidfile /var/run/jackd.pid "sh -c '${JACKD} ${JACKD_OPTS} > /dev/null &2>1'"
    RETVAL=$?
    echo
    return ${RETVAL}
}

stop() {
    echo -n $"Stopping jackd..."
    killproc ${JACKD}
    RETVAL=$?
    echo jackd stopped
    return ${RETVAL}
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        PID=`pgrep -U ${USER} jackd`
        if [ "" == "${PID}" ] ; then
            echo jackd is not running
        else
            echo "jackd is running, pid = ${PID}"
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|}"
        exit 1
esac

exit $RETVAL
